#cloud-config

hostname: "coreos1"
users:
  - name: "core"
    passwd: "$1$VN4eM2l8$chUy9jacF1Uupk.RePahh."
    groups:
      - "sudo"
      - "docker"
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFaIocmziJhl7pNS3eIY40C8/MsCOirYeYi/1gpbj3f+JIyVLmEWWkRWzWUiAANclFEKuGQ5eX7Ugam5PwuIuvNsL4ecFakDPX82fiMHnh+c4Q0ZqlMwL0FgbaZFy407Ewo97HvLuqHTYlWrExhaB1Bdgp2P1QbAwzkP6xOvMZ9PX1DSE6Wc8N+Ai2ukj85ZVka5MlKuswJTgWGAsTZtycfrMHzs2KyBl59KBmNQQI35vVdc2BDAwUI2cQG0NkYic8sSt/LriIgKg0vus2ImqZzNQh7ALruocq3n7ZF6QHKEFibBkp4xx/wtGvutWI1ysqvxZTsnnLEmZrgL+1MsAH core"

systemd:
  units:
    - name: etcd2.service
      enable: true

passwd:
  users:
    - name: core
      sshAuthorizedKeys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGdByTgSVHq
